---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: cast-db
          image: postgres:12.1-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: cast_db_password
            - name: POSTGRES_USER
              value: datascientest
            - name: POSTGRES_DB
              value: datascientest        
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres-data-movie
      volumes:
        - name: postgres-data-movie
          persistentVolumeClaim:
            claimName: postgres-data-movie  
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
  labels:
    app: cast-db
spec:
  type: NodePort
  ports:
    - name: cast-db
      port: 5432
      targetPort: 5432
  selector:
    app: cast-db
---
# apiVersion: v1
# kind: Secret
# metadata:
#  name: postgres-secret-cast
#  namespace: standard
#type: Opaque
#data:
#  postgres-username: YWRtaW4=
#  postgres-password: cGFzc3dvcmQ=
#  postgres-database: c3RvcmVkYg==