---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-cast
spec:
  accessModes:
  - {{ .Values.castdb.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.castdb.pvc.storage }}
status: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.castdb.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.castdb.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.castdb.name }}
    spec:
      containers:
        - name: {{ .Values.castdb.name }}
          image: postgres:12.1-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: {{ .Values.castdb.service.port }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.castdb.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.castdb.env.POSTGRES_USER }}
            - name: POSTGRES_DB
              value: {{ .Values.castdb.env.POSTGRES_DB }}        
          volumeMounts:
            - mountPath: {{ .Values.castdb.volumeMounts.mountPath }}   
              name: {{ .Values.castdb.volumeMounts.name }}  
      volumes:
        - name: {{ .Values.castdb.volumes.name }} 
          persistentVolumeClaim:
            claimName: {{ .Values.castdb.volumes.persistentVolumeClaim.claimName }}  
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.castdb.name }}
  labels:
    app: {{ .Values.castdb.name }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.castdb.name }}
      port: {{ .Values.castdb.service.port }}
      targetPort: {{ .Values.castdb.service.targetPort }}
  selector:
    app: {{ .Values.castdb.name }}
---
# apiVersion: v1
# kind: Secret
# metadata:
#  name: postgres-secret-cast
#  namespace: standard
#type: Opaque
#data:
#  postgres-username: YWRtaW4=
#  postgres-password: cGFzc3dvcmQ=
#  postgres-database: c3RvcmVkYg==