apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-data-movie
  name: postgres-data-movie
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.moviedb.app }} 
spec:
  replicas: {{ .Values.moviedb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.moviedb.app }} 
  template:
    metadata:
      labels:
        app: {{ .Values.moviedb.app }} 
    spec:
      containers:
        - name: {{ .Values.moviedb.app }} 
          image: {{ .Values.moviedb.image }} 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.moviedb.containerPort }} 
          env:
            - name: POSTGRES_DB
              value: {{ .Values.moviedb.env.POSTGRES_DB }} 
            - name: POSTGRES_PASSWORD
              value: {{ .Values.moviedb.env.POSTGRES_PASSWORD }} 
            - name: POSTGRES_USER
              value: {{ .Values.moviedb.env.POSTGRES_USER }} 
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres-data-movie
      volumes:
        - name: postgres-data-movie
          persistentVolumeClaim:
            claimName: postgres-data-movie 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moviedb.name }}
  labels:
    app: {{ .Values.moviedb.name }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.castdb.name }}
      port: {{ .Values.moviedb.service.port }}
      targetPort: {{ .Values.moviedb.service.targetPort }}
  selector:
    app: {{ .Values.moviedb.name }}
---