apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  selector:
    matchLabels:
      app: movie-db
  replicas: 1
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: movie_db_dev
        - name: POSTGRES_PASSWORD
          value: movie_db_password
        - name: POSTGRES_USER
          value: movie_db_username
        image: postgres:12.1-alpine
        imagePullPolicy: ""
        name: movie-db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgres-data-movie
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgres-data-movie
        persistentVolumeClaim:
          claimName: postgres-data-movie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-data-movie
  name: postgres-data-movie
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}